# -*- coding: utf-8 -*-
"""Lung Cancer Convolutional Network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEeLKdqYIv1U2ZMUD_7lSIFMKfRmXMOw
"""

import tensorflow as tf
import numpy as np

IMG_PXL_SIZE = 50
HM_SLICES = 20

import tensorflow.compat.v1 as tf

tf.disable_eager_execution()  # TF 2.x-এ placeholder চালানোর জন্য

n_classes = 2
input_features = 100  # আপনার ইমেজের বা ডেটার মোট ফিচারের সংখ্যা

# string 'float' এর জায়গায় tf.float32 ব্যবহার করা ভালো
x = tf.placeholder(tf.float32, shape=[None, input_features])
y = tf.placeholder(tf.float32, shape=[None, n_classes])

def convolutional_neural_network(x):
    weights = {'W_conv1':tf.Variable(tf.random_normal([5,5,5,1,32])),
               'W_conv2':tf.Variable(tf.random_normal([5,5,5,32,64])),
               'W_fc':tf.Variable(tf.random_normal([54080,1024])),
               'out':tf.Variable(tf.random_normal([1024, n_classes]))}

    biases = {'b_conv1':tf.Variable(tf.random_normal([32])),
               'b_conv2':tf.Variable(tf.random_normal([64])),
               'b_fc':tf.Variable(tf.random_normal([1024])),
               'out':tf.Variable(tf.random_normal([n_classes]))}

    x = tf.reshape(x, shape=[-1, IMG_PXL_SIZE, IMG_PXL_SIZE, HM_SLICES, 1])

    conv1 = tf.nn.relu(conv3d(x, weights['W_conv1']) + biases['b_conv1'])
    conv1 = maxpool3d(conv1)

    conv2 = tf.nn.relu(conv3d(conv1, weights['W_conv2']) + biases['b_conv2'])
    conv2 = maxpool3d(conv2)


    fc = tf.reshape(conv2,[-1, 54080])
    fc = tf.nn.relu(tf.matmul(fc, weights['W_fc'])+biases['b_fc'])
    fc = tf.nn.dropout(fc, keep_rate)

    output = tf.matmul(fc, weights['out'])+biases['out']

    return output

"""## Training Neural Netwrok

I tried training over the complete train set but my system broke down due to the heavy processing so I used chunks of data to train, the results are definitely not accurate because this model has not been trained on complete data but still it works pretty good.

** My system is a Core i7 with 12gigs of RAM and NVIDIA 1050Ti**
"""

import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

def train_neural_network(x, y):
    # ১. ডেটা লোড
    train_data = np.load('traindata-50-50-20.npy')
    test_data = np.load('testdata-50-50-20.npy')

    train = train_data
    test = test_data

    # ২. মডেল, লস এবং অপটিমাইজার
    prediction = convolutional_neural_network(x)
    cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=prediction, labels=y))
    optimizer = tf.train.AdamOptimizer().minimize(cost)

    hm_epochs = 5
    with tf.Session() as sess:
        # ৩. আপডেট করা ইনিশিয়ালাইজার
        sess.run(tf.global_variables_initializer())

        for epoch in range(hm_epochs):
            epoch_loss = 0
            success_total = 0
            attempt_total = 0

            for data in train:
                attempt_total += 1
                try:
                    # ৪. ব্যাচ ডাইমেনশন যুক্ত করা (Tensor shape ঠিক রাখার জন্য)
                    X = np.array([data[0]])
                    Y = np.array([data[1]])

                    _, c = sess.run([optimizer, cost], feed_dict={x: X, y: Y})
                    epoch_loss += c
                    success_total += 1

                except Exception as e:
                    print(f'Error occurred: {e}')

            print(f'Epoch {epoch+1} completed out of {hm_epochs} | loss: {epoch_loss} | success_rate: {success_total/attempt_total}')

        # ৫. একুরেসি ক্যালকুলেশন (test_data ব্যবহার করে)
        correct = tf.equal(tf.argmax(prediction, 1), tf.argmax(y, 1))
        accuracy = tf.reduce_mean(tf.cast(correct, 'float'))

        test_x = np.array([i[0] for i in test])
        test_y = np.array([i[1] for i in test])

        print('Accuracy:', accuracy.eval({x: test_x, y: test_y}))

# ফাংশন কল করার সময় x এবং y প্লেসহোল্ডার দুটিই পাস করতে হবে
# train_neural_network(x, y)

